module.exports = {
  VEHICLES: {
    READ: ['ADMIN', 'MANAGER', 'DRIVER', 'SAFETY_OFFICER', 'FINANCIAL_ANALYST'],
    READ_COST: ['ADMIN', 'MANAGER', 'FINANCIAL_ANALYST'],
    WRITE: ['ADMIN', 'MANAGER']
  },
  DRIVERS: {
    READ: ['ADMIN', 'MANAGER', 'SAFETY_OFFICER', 'DRIVER', 'FINANCIAL_ANALYST'],
    WRITE: ['ADMIN', 'MANAGER', 'DRIVER']
  },
  TRIPS: {
    READ: ['ADMIN', 'MANAGER', 'SAFETY_OFFICER', 'FINANCIAL_ANALYST', 'DRIVER'],
    WRITE: ['ADMIN', 'MANAGER', 'DRIVER']
  },
  MAINTENANCE: {
    READ: ['ADMIN', 'MANAGER', 'FINANCIAL_ANALYST', 'DRIVER', 'SAFETY_OFFICER'],
    READ_COST: ['ADMIN', 'MANAGER', 'FINANCIAL_ANALYST'],
    WRITE: ['ADMIN', 'MANAGER']
  },
  FUEL: {
    READ: ['ADMIN', 'MANAGER', 'FINANCIAL_ANALYST', 'DRIVER', 'SAFETY_OFFICER'],
    WRITE: ['ADMIN', 'MANAGER', 'DRIVER']
  },
  REPORTS: {
    FINANCIAL: ['ADMIN', 'MANAGER', 'FINANCIAL_ANALYST'],
    COMPLIANCE: ['ADMIN', 'MANAGER', 'SAFETY_OFFICER'],
    EXPORT: ['ADMIN', 'MANAGER', 'FINANCIAL_ANALYST']
  },
  USERS: {
    READ: ['ADMIN'],
    WRITE: ['ADMIN']
  }
};
